#!/bin/bash

echo '' > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS

(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q2_n10.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q2_n10.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q2_n20.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q2_n20.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q2_n30.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q2_n30.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q2_n40.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q2_n40.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q2_n50.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q2_n50.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q2_n60.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q2_n60.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q2_n70.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q2_n70.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q3_n10.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q3_n10.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q3_n20.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q3_n20.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q3_n30.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q3_n30.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q3_n40.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q3_n40.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q3_n50.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q3_n50.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q3_n60.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q3_n60.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q3_n70.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q3_n70.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q4_n10.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q4_n10.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q4_n20.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q4_n20.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q4_n30.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q4_n30.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q4_n40.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q4_n40.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q4_n50.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q4_n50.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q4_n60.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q4_n60.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q4_n70.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q4_n70.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q5_n10.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q5_n10.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q5_n20.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q5_n20.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q5_n30.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q5_n30.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q5_n40.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q5_n40.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q5_n50.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q5_n50.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q5_n60.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q5_n60.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
(nohup /usr/bin/time -v magma /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Input/q5_n70.m > /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Logs/q5_n70.log 2>&1 & echo $! >> /home/nguyen7/QuantumCode/QECC_FromQT/auto_run_theorem_3/Utilities/PIDS) &
wait
