#!/bin/bash

echo '' > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS"

(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q2_n10.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q2_n10.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q2_n15.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q2_n15.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q2_n20.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q2_n20.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q2_n25.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q2_n25.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q2_n30.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q2_n30.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q2_n35.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q2_n35.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q3_n10.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q3_n10.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q3_n15.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q3_n15.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q3_n20.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q3_n20.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q3_n25.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q3_n25.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q3_n30.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q3_n30.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q3_n35.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q3_n35.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q5_n10.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q5_n10.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q5_n15.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q5_n15.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q5_n20.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q5_n20.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q5_n25.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q5_n25.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q5_n30.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q5_n30.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q5_n35.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q5_n35.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q7_n10.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q7_n10.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q7_n15.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q7_n15.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q7_n20.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q7_n20.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q7_n25.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q7_n25.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q7_n30.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q7_n30.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q7_n35.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q7_n35.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q9_n10.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q9_n10.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q9_n15.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q9_n15.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q9_n20.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q9_n20.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q9_n25.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q9_n25.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q9_n30.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q9_n30.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
(nohup /usr/bin/time -v magma "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Input/q9_n35.m" > "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Logs/q9_n35.log" 2>&1 & echo $! >> "/home/nguyen7/QuantumCode/CC_CodesAxiom2014/Utilities/PIDS") &
wait
